### PR TITLE
Fix typing dep

### PR DESCRIPTION
**Pull request by ocefpaf**
`typing` is no longer available on Python >=3.6 so we need to add a pre-selector there and remove the `noarch` from this recipe :-(

### CODE REVIEW

**Comment by jakevdp** [comment]
Ah, bummer. Thanks for checking on this.

**Comment by ocefpaf** [comment]
> Ah, bummer. Thanks for checking on this.

No problem. (I'm working on the remaining py37 deps to re-start this and get it merged later today.)

**Comment by jakevdp** [comment]
Thanks!

**Comment by ocefpaf** [comment]
No problem. I also worked with @domoritz to pull the `vega 2.0` packages from the channel and that got the `conda-forge` `altair` package working again. Thanks @jakevdp and @domoritz for these packages!

**Comment by domoritz** [comment]
Thank you @ocefpaf for all your help!

**Pull request merged**
