### PR TITLE
Version 1.2.1

### PR DESCRIPTION
**Pull request by jakevdp**

### CODE REVIEW

**Comment by jakevdp** [comment]
The CircleCI tests failed because it thinks this branch is out of date... any ideas what might be going on?

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
@jakevdp, is this package pure python? If so, consider making it `noarch`. See https://conda-forge.org/docs/meta.html#building-noarch-packages
You can do it with a github comment as mentioned in in https://conda-forge.org/docs/webservice.html#conda-forge-admin-please-add-noarch-python

**Comment by jakevdp** [comment]
@conda-forge-admin, please add noarch: python

**Comment by jakevdp** [comment]
Assuming this is OK to merge?

**Comment by isuruf** [comment]
Looks good to me

**Comment by jakevdp** [comment]
Thanks!

**Pull request merged**
