### PR TITLE
Avoid installing vegafusion 2rc

### PR DESCRIPTION
**Pull request by joelostblom**
There was [a new 2.0 RC of vegafusion published yesterday](https://anaconda.org/conda-forge/vegafusion), which is not compatible with the current release of altair, so we need to avoid installing it as a dependency.

CC @jonmmease to confirm

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by joelostblom** [comment]
@conda-forge-admin, please rerender

**Comment by jonmmease** [comment]
Thanks @joelostblom!  I was expecting that conda solvers wouldn't pull in the RC automatically, were you seeing this happen? Either way, adding the upper bound now is great.

**Comment by joelostblom** [comment]
A few of my students installed `altair-all` today and they ended up with Vegafusion 2.0, so I believe conda is pulling in the RC when looking at the dependencies to install.

**Comment by joelostblom** [comment]
@ocefpaf I'm unsure why the tests are failing here. Do you know if it is a CI-related issue and we can merge anyways, or is it something that should be fixed in this PR?

**Comment by jonmmease** [comment]
The error makes it look like the test is being run with python 3.13 (See https://github.com/vega/altair/issues/3620#issuecomment-2489833450). I just tried adding a version constraint on python itself.

**Comment by jonmmease** [comment]
That did it, we need to remember to drop the constraint once 3.13 is supported. Merging and opening an issue.

**Pull request merged**
