### PR TITLE
altair v4.2.2 without jsonschema upper bound

### PR DESCRIPTION
**Pull request by jtilly**
Closes #44

See https://github.com/conda-forge/altair-feedstock/pull/43#issuecomment-1406957834

### CODE REVIEW

**Comment by jtilly** [comment]
@joelostblom @binste is this good to go?

Would you mind adding yourself as maintainer to this feedstock? Then you can just approve/merge future PRs like this yourself?

**Comment by ocefpaf** [comment]
> @joelostblom @binste is this good to go?

I think you got the wrong folks here. You can ping the @conda-forge/altair team instead.
PS: merging this, we can add you in another PR. You can even use the bot command to do so.

**Comment by mattijn** [comment]
Thanks for merging this! As you have noticed @jtilly, we are currently in an ongoing organic reorganization with the altair maintainers. Should gradually improve in the coming period. Thanks for this reminder!

**Comment by ocefpaf** [comment]
> Thanks for merging this! As you have noticed @jtilly, we are currently in an ongoing organic reorganization with the altair maintainers. Should gradually improve in the coming period. Thanks for this reminder!

Cool. Please consider adding yourselves as maintainers here.

**Pull request merged**
